name: Feature request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Thank you for your suggestion!

  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: Describe the inconvenience or limitation you are experiencing
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
    validations:
      required: false
